version: 2
jobs:
  build:
    docker:
      - image: poldrack/statsthinking21
    steps:
      - add_ssh_keys:
          fingerprints:
            - "97:93:7d:ff:2f:8f:20:21:ce:f7:1c:f7:f5:53:31:11"
      - checkout
      - run:
           name: rendering pdf
           command: |
             make render-pdf
           no_output_timeout: 1200
      - run:
           name: rendering epub
           command: |
             make render-epub
           no_output_timeout: 1200
      - run:
           name: rendering gitbook
           command: |
             make render-gitbook
           no_output_timeout: 1200
      - run:
           name: check out site repo
           command: |
             cd /tmp
             ssh-keyscan github.com >> ~/.ssh/known_hosts
             git clone git@github.com:statsthinking21/statsthinking21-R-site.git
             cd statsthinking21-R-site
             cp -r ~/project/_book/* . 
             git add .
             git config --global user.email poldrack@gmail.com
             git config --global user.name "Russ Poldrack"
             git commit -m"automated update"
             git push origin master

